repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.0
    hooks:
      - id: clang-format
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black